name: Unzip Files

on:
  push:
    paths:
      - '**/*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the environment

    steps:
    - name: Checkout the code  # Step to check out the repository code
      uses: actions/checkout@v2

    - name: Install unzip utility  # Step to ensure the unzip tool is available
      run: sudo apt-get install -y unzip

    - name: Unzip all zip files in the repository  # Step to unzip any found zip files
      run: |
        for file in $(find . -name '*.zip'); do
          unzip "$file" -d "${file%.*}"
        done

    - name: Commit unzipped files back to the repository  # Step to commit the unzipped content back to the repo
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Unzipped files"
        git push
