name: Unzip Files and Commit Only Unzipped Content

on:
  push:
    paths:
      - '**/*.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install unzip utility
      run: sudo apt-get install -y unzip

    - name: Unzip files and delete the zip file
      run: |
        for file in $(find . -name '*.zip'); do
          echo "Unzipping $file..."
          unzip -o "$file" -d "${file%.*}" || echo "Failed to unzip $file"
          echo "Deleting $file..."
          rm "$file"
        done

    - name: Commit unzipped content
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Added unzipped files"
        git push
